---
title: "Lab5_with_exercises"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
Confirmed_State_3_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>%
    filter (Country_Region == "US") %>%
  group_by(Province_State, Country_Region) %>%
  summarise(Confirmed = sum(Confirmed))
```
```{r}
str(Confirmed_State_3_13)
```
 
```{r}
Confirmed_State_9_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>%
  filter(Country_Region == "US") %>%
  group_by(Province_State, Country_Region) %>%
  summarise(Confirmed = sum(Confirmed))
```

```{r}
str(Confirmed_State_9_13)
```

```{r}
setdiff(Confirmed_State_9_13$Province_State, Confirmed_State_3_13$Province_State)
```

```{r}
Confirmed_State_9_13 <- Confirmed_State_9_13 %>%
  filter(Province_State != "Recovered")
```

```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13, Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_3_13_9_13_joined)
```
```{r}
tail(Confirmed_State_3_13_9_13_joined, 5)
```

```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```

```{r}
Confirmed_State_3_13_9_13_joined <- full_join(Confirmed_State_3_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_3_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_3_13_9_13_joined)
```

```{r}
which(is.na(Confirmed_State_3_13_9_13_joined))
```

```{r}
Confirmed_State_3_13_9_13_joined_long <- Confirmed_State_3_13_9_13_joined %>%
  pivot_longer(-c(Province_State),
               names_to = "Date", values_to = "Confirmed")
```

```{r, fig.width = 5, fig.height = 10}
ggplot(Confirmed_State_3_13_9_13_joined_long, aes(x=Confirmed, y=Province_State)) + 
  geom_point(aes(color = Date))
```

```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
rename(Province_State = "Province/State",  Country_Region = "Country/Region")
```

```{r}
head(time_series_confirmed)
```

```{r} 
time_series_confirmed_long <- time_series_confirmed %>%
pivot_longer(-c(Province_State, Country_Region, Lat, Long),               
             names_to = "Date", values_to = "Confirmed")

```

```{r}
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")

```

```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
```

```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)
```

```{r}
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```

```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```

```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
head(time_series_long_joined)
```

```{r}
which(is.na(time_series_long_joined$Confirmed))

```

```{r}
which(is.na(time_series_long_joined$Deaths))
```

```{r}
library(lubridate)

```

```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
```

```{r}
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```

```{r}
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("China","Japan", "Korea, South",
                                "Italy","Spain", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

```{r}
time_series_long_joined %>% 
    group_by(Country_Region,Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    filter (Country_Region %in% c("China","France","Italy", 
                                "Korea, South", "US")) %>% 
    ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```

```{r}
time_series_long_joined_counts %>% 
  group_by(Country_Region, Report_Type, Date) %>% 
  summarise(Counts = sum(Counts)) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = log2(Counts), fill = Report_Type, color = Report_Type)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Cases")
```

```{r}
#Exercise 1 - see in the Data Visualization file
```

```{r}
#Exercise 2 
Confirmed_State_6_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter(Country_Region == "US") %>%
  group_by(Province_State, Country_Region) %>%
  summarise(Confirmed = sum(Confirmed)) 
```


```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_3_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)

```
```{r, fig.width=10, fig.height=10}
ggplot(Confirmed_State_6_13_9_13_joined, aes(x = Confirmed_6_13_2020, y = Province_State)) + 
  geom_bar(stat="identity")
```
```{r, fig.width=10, fig.height=10}
ggplot(Confirmed_State_6_13_9_13_joined, aes(x = Confirmed_9_13_2020, y = Province_State)) + 
  geom_bar(stat="identity")
```




```{r, fig.width=10, fig.height=10}
#Exercise 3
ggplot(Confirmed_State_6_13_9_13_joined, aes(x = Confirmed_6_13_2020, y = Province_State)) + 
  geom_bar(stat="identity") + 
  xlab("Confirmed COVID Cases 6/13/2020") + 
  ylab("USA Province or State")
```

```{r, fig.width=10, fig.height=10}
ggplot(Confirmed_State_6_13_9_13_joined, aes(x = Confirmed_9_13_2020, y = Province_State)) + 
  geom_bar(stat="identity") + 
  xlab("Confirmed COVID Cases 9/13/2020") + 
  ylab("USA Province or State")
```



```{r}
#Exercise 4
time_series_long_joined %>%
arrange(Date) %>%
group_by(Date) %>%
summarise(sumDeaths = sum(Deaths)) %>%
  ggplot(aes(x=Date, y =sumDeaths)) + 
  geom_point()

```

```{r}
#Exercise 5
time_series_long_joined_deathsconfirmed <- time_series_long_joined %>%
  mutate(deaths_confirmed = Deaths/Confirmed)
```

```{r}
#Exercise 6
time_series_long_joined_deathsconfirmed %>%
  filter(Country_Region == "US") %>%
  ggplot(aes(x=Date, y = deaths_confirmed)) + 
  geom_bar(stat="identity") + 
  ylab("US Deaths/confirmed")
```
```{r}
#Exercise 7 
time_series_long_joined %>%
  group_by(Country_Region) %>%
summarise(SumDeaths = sum(Deaths)) %>%
arrange(desc(SumDeaths)) %>%
filter(SumDeaths > 4686039) %>%
 ggplot(aes(x=Country_Region, y=SumDeaths)) + 
  geom_bar(stat="identity") 
```

```{r, fig.height=5}
#Exercise 8 
time_series_long_joined %>%
filter(Country_Region %in% c("US", "Brazil", "India", "Mexico", "United Kingdom", "Italy", "France", "Spain", "Iran", "Peru")) %>%
ggplot(aes(x = Date,  y = Deaths)) + 
    geom_bar(stat="identity") +
    ggtitle("COVID-19 Deaths in Top 10 Countries") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

```{r}
#Exercise 9
time_series_long_joined %>%
filter(Country_Region == "US") %>%
group_by(Province_State) %>%
summarise(sumConfirmed = sum(Confirmed)) %>%
ggplot(aes(x = Province_State,  y = sumConfirmed)) + 
    geom_point() +
    ggtitle("COVID-19 Confirmed Cases per State") +
    facet_wrap(~Province_State, ncol=2, scales="free_y")
```

```{r, fig.height=5}
#Exercise10 
time_series_long_joined %>%
filter(Country_Region %in% c("US", "Brazil", "India", "Mexico", "United Kingdom", "Italy", "France", "Spain", "Iran", "Peru")) %>%
ggplot(aes(x = Date,  y = Deaths)) + 
    geom_bar(stat="identity") +
    ggtitle("COVID-19 Deaths in Top 10 Countries") +
    facet_wrap(~Country_Region, ncol=2, scales="free_y") + 
  theme_test()
```
```

