---
title: "Lab7"
output: html_document
---
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
library("BiocStyle")
library("knitr")
library("rmarkdown")
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE,
               cache = FALSE, fig.width = 5, fig.height = 5)
```

##loadairway
#load example data set
```{r}
library("airway")
```
##dir
```{r}
dir <- system.file("extdata", package="airway", mustWork=TRUE)
```

```{r}
## ----list.files---------------------------------------------------------------
list.files(dir)
list.files(file.path(dir, "quants"))

```

```{r}
## ----sampleinfo---------------------------------------------------------------
csvfile <- file.path(dir, "sample_table.csv")
coldata <- read.csv(csvfile, row.names=1, stringsAsFactors=FALSE)
coldata
```


```{r}
## ----makecoldata--------------------------------------------------------------
#make name and files columns
coldata <- coldata[1:2,]
coldata$names <- coldata$Run
coldata$files <- file.path(dir, "quants", coldata$names, "quant.sf.gz")
file.exists(coldata$files)
```
```{r}
## ----tximeta, message=TRUE----------------------------------------------------
#locating and downloading relevant annotation at the transcript level
library("tximeta")
se <- tximeta(coldata)
```

```{r}
## ----lookse-------------------------------------------------------------------
#summarize transcript level information to gene level information
gse <- summarizeToGene(se)
dim(gse)
head(rownames(gse))
```

```{r}
## ----summarize, message=TRUE--------------------------------------------------
gse <- summarizeToGene(se)
```

```{r}
## ----lookgse------------------------------------------------------------------
dim(gse)
head(rownames(gse))
```

```{r}
## ----sumexp, echo=FALSE-------------------------------------------------------
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(0,100),ylim=c(0,100),bty="n",
     type="n",xlab="",ylab="",xaxt="n",yaxt="n")
polygon(c(45,90,90,45),c(5,5,70,70),col="pink",border=NA)
polygon(c(45,90,90,45),c(68,68,70,70),col="pink3",border=NA)
text(67.5,40,"assay(s)")
text(67.5,35,'e.g. "counts", ...')
polygon(c(10,40,40,10),c(5,5,70,70),col="skyblue",border=NA)
polygon(c(10,40,40,10),c(68,68,70,70),col="skyblue3",border=NA)
text(25,40,"rowRanges")
polygon(c(45,90,90,45),c(75,75,95,95),col="palegreen",border=NA)
polygon(c(45,47,47,45),c(75,75,95,95),col="palegreen3",border=NA)
text(67.5,85,"colData")
```

```{r}
## ----loadfullgse--------------------------------------------------------------
data(gse)
gse
```

```{r}
## ----assaysgse----------------------------------------------------------------
#Measuring counts
assayNames(gse)
head(assay(gse), 3)
colSums(assay(gse))
```

```{r}
## ----rowrangesgse-------------------------------------------------------------
#genes for first five and last five genes
rowRanges(gse)
```

```{r}
## ----lookseqinfo--------------------------------------------------------------
#metadata in the seqinfo slot
seqinfo(rowRanges(gse))
```

```{r}
## ----coldatagse---------------------------------------------------------------
#input data frame,sample/donor information
colData(gse)
```

```{r}
## ----gsevars------------------------------------------------------------------
#observing columns with $
gse$donor
gse$condition
```

```{r}
## ----gsevarsrename------------------------------------------------------------
#renaming variables
gse$cell <- gse$donor
gse$dex <- gse$condition
```

```{r}
## ----renamelevels-------------------------------------------------------------
#make sure to keep levels in the same order when renaming! 
levels(gse$dex)
# when renaming levels, the order must be preserved!
levels(gse$dex) <- c("untrt", "trt")
```

```{r}
## ----gsedex-------------------------------------------------------------------
library("magrittr")
gse$dex %<>% relevel("untrt")
gse$dex
```

```{r}
## ----explaincmpass, eval = FALSE----------------------------------------------
#  gse$dex <- relevel(gse$dex, "untrt")
```


```{r}
## ----countreads---------------------------------------------------------------
round( colSums(assay(gse)) / 1e6, 1 )
```

```{r}
## ----loaddeseq2---------------------------------------------------------------
#Construct a DESeq dataset
library("DESeq2")
```

```{r}
## ----makedds------------------------------------------------------------------
dds <- DESeqDataSet(gse, design = ~ cell + dex)
```

```{r}
## -----------------------------------------------------------------------------
#fragment counts
countdata <- round(assays(gse)[["counts"]])
head(countdata, 3)
```

```{r}
## -----------------------------------------------------------------------------
#information about samples
coldata <- colData(gse)
```

```{r}
## -----------------------------------------------------------------------------
#construct the DESeqDataSet object
ddsMat <- DESeqDataSetFromMatrix(countData = countdata,
                                 colData = coldata,
                                 design = ~ cell + dex)
```

```{r}
## -----------------------------------------------------------------------------
#pre-filtering to remove rows with all 0s or only 1 count
nrow(dds)
keep <- rowSums(counts(dds)) > 1
dds <- dds[keep,]
nrow(dds)
```

```{r}
## -----------------------------------------------------------------------------
# at least 3 samples with a count of 10 or higher
keep <- rowSums(counts(dds) >= 10) >= 3
```

```{r}
## ----meanSdCts----------------------------------------------------------------
#sample possion data PCA plot
#don't change ranks = TRUE!
lambda <- 10^seq(from = -1, to = 2, length = 1000)
cts <- matrix(rpois(1000*100, lambda), ncol = 100)
library("vsn")
meanSdPlot(cts, ranks = FALSE)
```

```{r}
## ----meanSdLogCts-------------------------------------------------------------
#log scale cts + 1
#make sure you have the +1!
log.cts.one <- log2(cts + 1)
meanSdPlot(log.cts.one, ranks = FALSE)
```

```{r}
## ----vst----------------------------------------------------------------------
#transformed values are no longer counts, stored in the assay column
#coldata is still accessible
#vst is better for medium-large size data sets 
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)
colData(vsd)
```

```{r}
## ----rlog---------------------------------------------------------------------
#rlog is better for small data sets. Good for high sequence depth variability
#bind = FALSE means that differences between cell lines and treatments won't contribute to the expected variance-mean trend of the experiment
rld <- rlog(dds, blind = FALSE)
head(assay(rld), 3)
```

```{r}
## ----transformplot, fig.width = 6, fig.height = 2.5---------------------------
library("dplyr")
library("ggplot2")
```

```{r}
#accounts for sequencing depth
dds <- estimateSizeFactors(dds)
```

```{r}
#normalized=TRUE used for sequencing depth correction
df <- bind_rows(
  as_data_frame(log2(counts(dds, normalized=TRUE)[, 1:2]+1)) %>%
         mutate(transformation = "log2(x + 1)"),
  as_data_frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"),
  as_data_frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"))
```

```{r}
colnames(df)[1:2] <- c("x", "y")  
```

```{r}
lvls <- c("log2(x + 1)", "vst", "rlog")
df$transformation <- factor(df$transformation, levels=lvls)
```

```{r}
#scatterplot of transformed counts for two samples 
ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) +
  coord_fixed() + facet_grid( . ~ transformation)
```

```{r}
## -----------------------------------------------------------------------------
sampleDists <- dist(t(assay(vsd)))
sampleDists
```

```{r}
## -----------------------------------------------------------------------------
library("pheatmap")
library("RColorBrewer")
```

```{r}
## ----distheatmap, fig.width = 6.1, fig.height = 4.5---------------------------
#how to make a heat map of sample to sample distances
#make sure to manually put in sampDists
sampleDistMatrix <- as.matrix( sampleDists )
rownames(sampleDistMatrix) <- paste( vsd$dex, vsd$cell, sep = " - " )
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colors)
```

```{r}
## -----------------------------------------------------------------------------
library("PoiClaClu")
poisd <- PoissonDistance(t(counts(dds)))

## ----poisdistheatmap, fig.width = 6.1, fig.height = 4.5-----------------------
#heat map using possion distance between samples
samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix) <- paste( dds$dex, dds$cell, sep=" - " )
colnames(samplePoisDistMatrix) <- NULL
pheatmap(samplePoisDistMatrix,
         clustering_distance_rows = poisd$dd,
         clustering_distance_cols = poisd$dd,
         col = colors)
```

```{r}
## ----plotpca, fig.width=6, fig.height=4.5-------------------------------------
#PCA plot using vst data
plotPCA(vsd, intgroup = c("dex", "cell"))
```

```{r}
## -----------------------------------------------------------------------------
pcaData <- plotPCA(vsd, intgroup = c( "dex", "cell"), returnData = TRUE)
pcaData
percentVar <- round(100 * attr(pcaData, "percentVar"))
```

```{r}
## ----ggplotpca, fig.width=6, fig.height=4.5-----------------------------------
#PCA plot with vst data and color corresponding to treatment and shape is cell line
ggplot(pcaData, aes(x = PC1, y = PC2, color = dex, shape = cell)) +
  geom_point(size =3) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  coord_fixed() +
  ggtitle("PCA with VST data")
```

```{r}
## -----------------------------------------------------------------------------
#generalized PCA
library("glmpca")
gpca <- glmpca(counts(dds), L=2)
gpca.dat <- gpca$factors
gpca.dat$dex <- dds$dex
gpca.dat$cell <- dds$cell
```

```{r}
## ----glmpca, fig.width=6, fig.height=4.5--------------------------------------
#generalized PCA
ggplot(gpca.dat, aes(x = dim1, y = dim2, color = dex, shape = cell)) +
  geom_point(size =3) + coord_fixed() + ggtitle("glmpca - Generalized PCA")
```

```{r}
## ----mdsvst, fig.width=6, fig.height=4.5--------------------------------------
mds <- as.data.frame(colData(vsd))  %>%
         cbind(cmdscale(sampleDistMatrix))
ggplot(mds, aes(x = `1`, y = `2`, color = dex, shape = cell)) +
  geom_point(size = 3) + coord_fixed() + ggtitle("MDS with VST data")
```

```{r}
## ----mdspois, fig.width=6, fig.height=4.5-------------------------------------
#multi dimensional scaling base function in R 
#good for when you only have a matrix of distances 
mds <- as.data.frame(colData(vsd))  %>%
         cbind(cmdscale(sampleDistMatrix))
ggplot(mds, aes(x = `1`, y = `2`, color = dex, shape = cell)) +
  geom_point(size = 3) + coord_fixed() + ggtitle("MDS with VST data")

mdsPois <- as.data.frame(colData(dds)) %>%
   cbind(cmdscale(samplePoisDistMatrix))
ggplot(mdsPois, aes(x = `1`, y = `2`, color = dex, shape = cell)) +
  geom_point(size = 3) + coord_fixed() + ggtitle("MDS with PoissonDistances")
```

```{r}
## ----airwayDE-----------------------------------------------------------------
#running analysis on raw counts 
#steps include estimation of size factors or controlling for differences in sequencing depth,  estimation of dispersion values for each gene and fitting a generalized linear  model 
dds <- DESeq(dds)
```

```{r}
## -----------------------------------------------------------------------------
#the estimated log2 fold changes and p values for the last variable in the design formula. If there are more than 2 levels for this variable, results will extract the results table for a comparison of the last level over the first level. The comparison is printed at the top of the output: dex trt vs untrt
res <- results(dds)
res
```

```{r}
## -----------------------------------------------------------------------------
#removing contrast argument 
res <- results(dds, contrast=c("dex","trt","untrt"))
```

```{r}
## -----------------------------------------------------------------------------
#baseMean = average of normalized count values divided by size factors for all samples in the DESeqDataSet. 
#all other columns are a specific contrast 
#this does not make sense to me 
mcols(res, use.names = TRUE)
```

```{r}
## -----------------------------------------------------------------------------
summary(res)
```

```{r}
## -----------------------------------------------------------------------------
res.05 <- results(dds, alpha = 0.05)
table(res.05$padj < 0.05)
```

```{r}
## -----------------------------------------------------------------------------
resLFC1 <- results(dds, lfcThreshold=1)
table(resLFC1$padj < 0.1)
```

```{r}
## -----------------------------------------------------------------------------
results(dds, contrast = c("cell", "N061011", "N61311"))
```

```{r}
## ----sumres-------------------------------------------------------------------
sum(res$pvalue < 0.05, na.rm=TRUE)
sum(!is.na(res$pvalue))
```

```{r}
## -----------------------------------------------------------------------------
sum(res$padj < 0.1, na.rm=TRUE)
```

```{r}
## -----------------------------------------------------------------------------
#strongest downregulation
resSig <- subset(res, padj < 0.1)
head(resSig[ order(resSig$log2FoldChange), ])
```

```{r}
## -----------------------------------------------------------------------------
#strongest upregulation because used decreaseing = TRUE 
head(resSig[ order(resSig$log2FoldChange, decreasing = TRUE), ])
```

```{r}
## ----plotcounts---------------------------------------------------------------
#as arguments the DESeqDataSet, a gene name, and the group over which to plot the counts
topGene <- rownames(res)[which.min(res$padj)]
plotCounts(dds, gene = topGene, intgroup=c("dex"))
```

```{r}
## ----ggplotcountsjitter, fig.width = 4, fig.height = 3------------------------
#must have returnData = TRUE for plot to show up
library("ggbeeswarm")
geneCounts <- plotCounts(dds, gene = topGene, intgroup = c("dex","cell"),
                    returnData = TRUE    )
ggplot(geneCounts, aes(x = dex, y = count, color = cell)) +
  scale_y_log10() +  geom_beeswarm(cex = 3)
```

```{r}
## ----ggplotcountsgroup, fig.width = 4, fig.height = 3-------------------------
#Does not need returnData = TRUE ?? 
ggplot(geneCounts, aes(x = dex, y = count, color = cell, group = cell)) +
  scale_y_log10() + geom_point(size = 3) + geom_line()
```

```{r}
## ----plotma-------------------------------------------------------------------
#mean-difference plot, or a Bland-Altman plot
library("apeglm")
resultsNames(dds)
res <- lfcShrink(dds, coef="dex_trt_vs_untrt", type="apeglm")
plotMA(res, ylim = c(-5, 5))
```

```{r}
## ----plotmaNoShr--------------------------------------------------------------
res.noshr <- results(dds, name="dex_trt_vs_untrt")
plotMA(res.noshr, ylim = c(-5, 5))
```

```{r}
## ----plotmalabel--------------------------------------------------------------
plotMA(res, ylim = c(-5,5))
topGene <- rownames(res)[which.min(res$padj)]
with(res[topGene, ], {
  points(baseMean, log2FoldChange, col="dodgerblue", cex=2, lwd=2)
  text(baseMean, log2FoldChange, topGene, pos=2, col="dodgerblue")
})
```

```{r}
## ----histpvalue2--------------------------------------------------------------
hist(res$pvalue[res$baseMean > 1], breaks = 0:20/20,
     col = "grey50", border = "white")
```

```{r}
## -----------------------------------------------------------------------------
library("genefilter")
topVarGenes <- head(order(rowVars(assay(vsd)), decreasing = TRUE), 20)
```

```{r}
## ----genescluster-------------------------------------------------------------
mat  <- assay(vsd)[ topVarGenes, ]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(vsd)[, c("cell","dex")])
pheatmap(mat, annotation_col = anno)
```

```{r}
## ----sensitivityovermean, fig.width=6-----------------------------------------
#The ratio of small p values for genes binned by mean normalized count
#quantile function creates bins 
#bin genes by base mean using cut 
#rename levels using the midpoint 
#calculate ratio of p values 
#plot the ratios 
qs <- c(0, quantile(resLFC1$baseMean[resLFC1$baseMean > 0], 0:6/6))
bins <- cut(resLFC1$baseMean, qs)
levels(bins) <- paste0("~", round(signif((qs[-1] + qs[-length(qs)])/2, 2)))
fractionSig <- tapply(resLFC1$pvalue, bins, function(p)
                          mean(p < .05, na.rm = TRUE))
barplot(fractionSig, xlab = "mean normalized count",
                     ylab = "fraction of small p values")
```

```{r}
## ---- eval=FALSE--------------------------------------------------------------
#  library("IHW")
#  res.ihw <- results(dds, filterFun=ihw)
```

```{r}
## -----------------------------------------------------------------------------
library("AnnotationDbi")
library("org.Hs.eg.db")
```

```{r}
## -----------------------------------------------------------------------------
columns(org.Hs.eg.db)
```

```{r}
## -----------------------------------------------------------------------------
ens.str <- substr(rownames(res), 1, 15)
res$symbol <- mapIds(org.Hs.eg.db,
                     keys=ens.str,
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
res$entrez <- mapIds(org.Hs.eg.db,
                     keys=ens.str,
                     column="ENTREZID",
                     keytype="ENSEMBL",
                     multiVals="first")
```

```{r}
## -----------------------------------------------------------------------------
resOrdered <- res[order(res$pvalue),]
head(resOrdered)
```

```{r}
## ----eval=FALSE---------------------------------------------------------------
#  resOrderedDF <- as.data.frame(resOrdered)[1:100, ]
#  write.csv(resOrderedDF, file = "results.csv")
```

```{r}
## ----eval=FALSE---------------------------------------------------------------
#  library("ReportingTools")
#  htmlRep <- HTMLReport(shortName="report", title="My report",
#                        reportDirectory="./report")
#  publish(resOrderedDF, htmlRep)
#  url <- finish(htmlRep)
#  browseURL(url)
```

```{r}
## -----------------------------------------------------------------------------
resGR <- lfcShrink(dds, coef="dex_trt_vs_untrt", type="apeglm", format="GRanges")
resGR
```

```{r}
## -----------------------------------------------------------------------------
ens.str <- substr(names(resGR), 1, 15)
resGR$symbol <- mapIds(org.Hs.eg.db, ens.str, "SYMBOL", "ENSEMBL")
```

```{r}
## -----------------------------------------------------------------------------
library("Gviz")
```

```{r}
## -----------------------------------------------------------------------------
window <- resGR[topGene] + 1e6
strand(window) <- "*"
resGRsub <- resGR[resGR %over% window]
naOrDup <- is.na(resGRsub$symbol) | duplicated(resGRsub$symbol)
resGRsub$group <- ifelse(naOrDup, names(resGRsub), resGRsub$symbol)

```

```{r}
## -----------------------------------------------------------------------------
status <- factor(ifelse(resGRsub$padj < 0.05 & !is.na(resGRsub$padj),
                        "sig", "notsig"))

```

```{r}
## ----gvizplot-----------------------------------------------------------------
options(ucscChromosomeNames = FALSE)
g <- GenomeAxisTrack()
a <- AnnotationTrack(resGRsub, name = "gene ranges", feature = status)
d <- DataTrack(resGRsub, data = "log2FoldChange", baseline = 0,
               type = "h", name = "log2 fold change", strand = "+")
plotTracks(list(g, d, a), groupAnnotation = "group",
           notsig = "grey", sig = "hotpink")
```

```{r}
## -----------------------------------------------------------------------------
library("sva")
```

```{r}
## -----------------------------------------------------------------------------
dat  <- counts(dds, normalized = TRUE)
idx  <- rowMeans(dat) > 1
dat  <- dat[idx, ]
mod  <- model.matrix(~ dex, colData(dds))
mod0 <- model.matrix(~   1, colData(dds))
svseq <- svaseq(dat, mod, mod0, n.sv = 2)
svseq$sv
```

```{r}
## ----svaplot------------------------------------------------------------------
par(mfrow = c(2, 1), mar = c(3,5,3,1))
for (i in 1:2) {
  stripchart(svseq$sv[, i] ~ dds$cell, vertical = TRUE, main = paste0("SV", i))
  abline(h = 0)
 }
```

```{r}
## -----------------------------------------------------------------------------
ddssva <- dds
ddssva$SV1 <- svseq$sv[,1]
ddssva$SV2 <- svseq$sv[,2]
design(ddssva) <- ~ SV1 + SV2 + dex
```

```{r}
## -----------------------------------------------------------------------------
library("RUVSeq")
```

```{r}
## -----------------------------------------------------------------------------
set <- newSeqExpressionSet(counts(dds))
idx  <- rowSums(counts(set) > 5) >= 2
set  <- set[idx, ]
set <- betweenLaneNormalization(set, which="upper")
not.sig <- rownames(res)[which(res$pvalue > .1)]
empirical <- rownames(set)[ rownames(set) %in% not.sig ]
set <- RUVg(set, empirical, k=2)
pData(set)
```

```{r}
## ----ruvplot------------------------------------------------------------------
par(mfrow = c(2, 1), mar = c(3,5,3,1))
for (i in 1:2) {
  stripchart(pData(set)[, i] ~ dds$cell, vertical = TRUE, main = paste0("W", i))
  abline(h = 0)
 }
```

```{r}
## -----------------------------------------------------------------------------
ddsruv <- dds
ddsruv$W1 <- set$W_1
ddsruv$W2 <- set$W_2
design(ddsruv) <- ~ W1 + W2 + dex

```

```{r}
## -----------------------------------------------------------------------------
library("fission")
data("fission")
ddsTC <- DESeqDataSet(fission, ~ strain + minute + strain:minute)
```

```{r}
## ----fissionDE----------------------------------------------------------------
ddsTC <- DESeq(ddsTC, test="LRT", reduced = ~ strain + minute)
resTC <- results(ddsTC)
resTC$symbol <- mcols(ddsTC)$symbol
head(resTC[order(resTC$padj),], 4)
```

```{r}
## ----fissioncounts, fig.width=6, fig.height=4.5-------------------------------
fiss <- plotCounts(ddsTC, which.min(resTC$padj), 
                   intgroup = c("minute","strain"), returnData = TRUE)
fiss$minute <- as.numeric(as.character(fiss$minute))
ggplot(fiss,
  aes(x = minute, y = count, color = strain, group = strain)) + 
  geom_point() + stat_summary(fun.y=mean, geom="line") +
  scale_y_log10()
```

```{r}
## -----------------------------------------------------------------------------
resultsNames(ddsTC)
res30 <- results(ddsTC, name="strainmut.minute30", test="Wald")
res30[which.min(resTC$padj),]
```

```{r}
## -----------------------------------------------------------------------------
betas <- coef(ddsTC)
colnames(betas)

```

```{r}
## ----fissionheatmap-----------------------------------------------------------
topGenes <- head(order(resTC$padj),20)
mat <- betas[topGenes, -c(1,2)]
thr <- 3 
mat[mat < -thr] <- -thr
mat[mat > thr] <- thr
pheatmap(mat, breaks=seq(from=-thr, to=thr, length=101),
         cluster_col=FALSE)
```

```{r}
## -----------------------------------------------------------------------------
sessionInfo()
```


























































































